name: Build Liberty image with war file
run-name: ${{ github.actor }} triggered build
on: [push]
jobs:
  build-war-file:
    # Default token permissions
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      # Clone repository
      - uses: actions/checkout@v4
      # Run the gradle build to create the war file using the gradle wrapper
      # The build creates the war file
      - name: gradlew-build-war-file
        run: |
          ./gradlew --no-daemon war
          cp build/libs/*.war .
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: liberty-sampleapp:latest
